kind: ReplicationController
apiVersion: v1
metadata:
  name: tasks
spec:
  replicas: 1
  selector:
    component: tasks
  template:
    metadata:
      labels:
        component: tasks
    spec:
      containers:
        - name: tasks
          image: mjelen/flink:latest
          args: ["tasks"]
          ports:
            - containerPort: 6121
            - containerPort: 6122
            - containerPort: 50101
          resources:
            requests:
              cpu: 100m
